package com.HemlockStudiosWebsite.service;
import com.HemlockStudiosWebsite.repo.UserRepo;
import com.HemlockStudiosWebsite.entity.User;
import java.util.List;
import javax.security.auth.login.AccountNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;

@Service
public class UserService implements UserDetailsService{

    @Autowired
    UserRepo userRepo;

    public User save(User user) {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

	    return userRepo.save(user);
	}
	public User update(User user) throws Exception {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

        if(user.getId() != null) {
	        return userRepo.save(user);
        }

        throw new AccountNotFoundException("Account does not exist! id not present");
	}
    
    public User findById(Integer userId) throws Error {
        
    	// Find by is another predefined repo function, you can always find by the primary key
    	// when you use findById, its good practice to use the isPresent in an if check first
    	// It will tell you if a object was actually found, with true or false values, true if found, false is not
    	// It will always return an Optional Object, the user will be there if found, null if not
    	// If found, give the object back with a .get() to grab it off the Optional object
    	
        if(userRepo.findById(userId).isPresent()) {
            return userRepo.findById(userId).get();
        }
        
        // if user is not present, throw error so front end can handle it
        throw new Error("No user id present, User not found, send an id billy, dumbass");
        
    }
	public User findByEmail(String email) {
		return userRepo.findByEmail(email);
	}
	public List<User> findAll() {
		return userRepo.findAll();
	}

    public User signIn(User user) throws Exception {
		
		User loggedInUser = userRepo.signIn(user.getEmail(), user.getPassword());
		if(loggedInUser == null) {
			throw new Exception("User was not found");
		}

		return loggedInUser;

	}

    public void deleteById(Integer id) {
	 
        userRepo.deleteById(id);
	}

    public List<User> getAll()
    {
        return userRepo.findAll();
    }

	public User findByUsername(String username) throws UsernameNotFoundException {
		return userRepo.findByUsername(username)
			.orElseThrow(() -> new UsernameNotFoundException("User not found"));
	}


    public Boolean getNotificationStatus()
    {
      
        User currentUser = findUserByEmail();
        Boolean notificationStatus = currentUser.getNotificationsEnabled();
        return notificationStatus;
    }

    public void setNotificationStatus(){
        User currentUser = findUserByEmail();
        Boolean notificationStatus = currentUser.getNotificationsEnabled();
        if(notificationStatus == true)
        {
            currentUser.setNotificationsEnabled(false);
            userRepo.save(currentUser);
      
        } 
        else{
            currentUser.setNotificationsEnabled(true);
            userRepo.save(currentUser);
    }
    }

    public void deleteUserById(Integer id) {
        User user = userRepo.findById(id).orElse(null);
    if (user != null) {
        userRepo.deleteById(id);
    } else {
        throw new IllegalArgumentException("User not found.");
    }
    }


    public User updateUser(Integer id, String username, String email) {
        User user = userRepo.findById(id).orElse(null);
        
        user.setUsername(username);
        user.setEmail(email);
        return userRepo.save(user);
    }

    public User findUserByEmail() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    
        if (auth == null) {
            System.out.println("Authentication is null");
            return null;
        }
    
        Jwt jwt = (Jwt) auth.getPrincipal();
    
        if (jwt == null) {
            System.out.println("JWT is null");
            return null;
        }
    
        String email = jwt.getClaim("email");
    
        if (email == null) {
            System.out.println("Email claim is null");
            return null;
        }
    
        User currentUser = userRepo.findByEmail(email);
    
        if (currentUser == null) {
            System.out.println("User not found in database with email: " + email);
            return null;
        }
    
        return currentUser;
    }
    public User getUserById(Integer userId) {
        return userRepo.findById(userId)
        .orElseThrow(() -> new RuntimeException("User not found"));
    }

	@Override
public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
System.out.println("in the userdetail service");
return userRepo.findByUsername(username).orElseThrow(() -> new UsernameNotFoundException("user is not valid"));
}

    
    
}


