package com.HemlockStudiosWebsite.service;

import com.HemlockStudiosWebsite.repo.UserRepo;
import com.HemlockStudiosWebsite.entity.Cart;
import com.HemlockStudiosWebsite.entity.CreditCard;
import com.HemlockStudiosWebsite.entity.Product;
import com.HemlockStudiosWebsite.entity.User;

import java.util.List;

import javax.security.auth.login.AccountNotFoundException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.event.EventListener;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;



@Service
public class UserService implements UserDetailsService{

    @Autowired
    UserRepo userRepo;


    @Autowired
    CreditCardService creditCardService;


    public User save(User user) {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

	    return userRepo.save(user);
	}
	
	public User update(User user) throws Exception {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

        if(user.getId() != null) {
	        return userRepo.save(user);
        }

        throw new AccountNotFoundException("Account does not exist! id not present");
	}
    
    public User findById(Integer userId) throws Error {
        
    	// Find by is another predefined repo function, you can always find by the primary key
    	// when you use findById, its good practice to use the isPresent in an if check first
    	// It will tell you if a object was actually found, with true or false values, true if found, false is not
    	// It will always return an Optional Object, the user will be there if found, null if not
    	// If found, give the object back with a .get() to grab it off the Optional object
    	
        if(userRepo.findById(userId).isPresent()) {
            return userRepo.findById(userId).get();
        }
        
        // if user is not present, throw error so front end can handle it
        throw new Error("No user id present, User not found, send an id billy, dumbass");
        
    }

	public User findByEmail(String email) {
		return userRepo.findByEmail(email);
	}



	public List<User> findAll() {
		return userRepo.findAll();
	}

    public User signIn(User user) throws Exception {
		
		User loggedInUser = userRepo.signIn(user.getEmail(), user.getPassword());
		if(loggedInUser == null) {
			throw new Exception("User was not found");
		}

		return loggedInUser;

	}

    public void deleteById(Integer id) {
	 
        userRepo.deleteById(id);
	}

    public List<User> getAll()
    {
        return userRepo.findAll();
    }

	public User findByUsername(String username) throws UsernameNotFoundException {
		return userRepo.findByUsername(username)
			.orElseThrow(() -> new UsernameNotFoundException("User not found"));
	}

    public void deleteUserById(Integer id) {
        User user = userRepo.findById(id).orElse(null);
    if (user != null) {
        
        List<Product> favoriteProducts = user.getFavoriteProducts();
        if (favoriteProducts != null) {
            favoriteProducts.clear();
            user.setFavoriteProducts(favoriteProducts);
            userRepo.save(user);
        }

        userRepo.deleteById(id);
    } else {
        throw new IllegalArgumentException("User not found.");
    }
    }


    public User updateUser(Integer id, String username, String email) {
        User user = userRepo.findById(id).orElse(null);
        
        user.setUsername(username);
        user.setEmail(email);
        return userRepo.save(user);
    }
    
    public Cart getCartByUserId(Integer id) {
        User user = userRepo.findById(id)
        .orElseThrow(() -> new RuntimeException("User not found with id"));
        return user.getCart();
    }

    public User findUserByEmail() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    
        if (auth == null) {
            System.out.println("Authentication is null");
            return null;
        }
    
        Jwt jwt = (Jwt) auth.getPrincipal();
    
        if (jwt == null) {
            System.out.println("JWT is null");
            return null;
        }
    
        String email = jwt.getClaim("email");
    
        if (email == null) {
            System.out.println("Email claim is null");
            return null;
        }
    
        User currentUser = userRepo.findByEmail(email);
    
        if (currentUser == null) {
            System.out.println("User not found in database with email: " + email);
            return null;
        }
    
        return currentUser;
    }
    
 



    public User getUserById(Integer userId) {
        return userRepo.findById(userId)
        .orElseThrow(() -> new RuntimeException("User not found"));
    }

    public void addCreditCard(String cardNumber, String expirationYear, String  expirationMonth, String cardHolderName, String cvv) {
       // Get authentication
       System.out.println("in the add credit card SERVICE path");
       Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        Jwt jwt = (Jwt) auth.getPrincipal();
        String email = jwt.getClaim("email");
       User currentUser = userRepo.findByEmail(email);
        CreditCard savedCreditCard = creditCardService.createCreditCard(cardNumber, cardHolderName, expirationMonth, expirationYear, cvv);
        currentUser.getWallet().add(savedCreditCard);
       userRepo.save(currentUser);
    }

    public void removeCreditCard(Integer creditCardId) {
        System.out.println("In the removeCreditCardPath in user service");
    
     Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        Jwt jwt = (Jwt) auth.getPrincipal();
        String email = jwt.getClaim("email");
       User currentUser = userRepo.findByEmail(email);
    
        CreditCard creditCard = creditCardService.getCreditCardById(creditCardId);
        System.out.println("Credit card to delete: " + creditCard);
        
        currentUser.getWallet().remove(creditCard);
        System.out.println("Credit card removed from wallet");
        
        userRepo.save(currentUser);
        System.out.println("User updated in database");
    
        creditCardService.deleteCreditCardById(creditCardId);
        System.out.println("Credit card deleted from credit card database");
    }

    public List<CreditCard> getCreditCards(Integer id) {
        User user = userRepo.findById(id)
        .orElseThrow(() -> new RuntimeException("User not found"));
        return user.getWallet();
    }

    public List<Product> getFavoriteProducts(Integer id) {
        User user = userRepo.findById(id)
        .orElseThrow(() -> new RuntimeException("User not found"));
        return user.getFavoriteProducts();
    }

	@Override
public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
System.out.println("in the userdetail service");
return userRepo.findByUsername(username).orElseThrow(() -> new UsernameNotFoundException("user is not valid"));
}

    
    
}


